version: "3"

services:
  grafana:
    image: dingjinlong/grafana:latest
    ports:
      - 3000:3000
    networks:
      - tb_net
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini  
    restart: always
    deploy:
      restart_policy:
        condition: any

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - tb_net
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    deploy:
      restart_policy:
        condition: any

  redis:
    image: redis:3.2
    command: ["redis-server"]
    ports:
      - 6379:6379
    networks:
      - tb_net
    restart: always
    deploy:
      restart_policy:
        condition: any

  node_exporter:
    image: dingjinlong/node_exporter:latest
    build: ./node_exporter
    command: ["python3", "run_api.py"]
    ports:
      - 9100:9100
    networks:
      - tb_net
    restart: always
    deploy:
      restart_policy:
        condition: any

  socket:
    image: dingjinlong/node_exporter:latest
    build: ./node_exporter
    command: ["python3", "run_socket.py"]
    ports:
      - 5858:5858
    networks:
      - tb_net
    restart: always
    deploy:
      restart_policy:
        condition: any

networks:
  tb_net:
volumes:
  tb_db:
