version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
      - tb_db:/data
    restart: always
    networks:
      - tb_net
    deploy:
      restart_policy:
        condition: any

  redis:
    image: redis:3.2
    command: ["redis-server"]
    ports:
      - 6379:6379
    networks:
      - tb_net
    restart: always
    deploy:
      restart_policy:
        condition: any

  node_exporter:
    image: dingjinlong/node_exporter:latest
    build: ./node_exporter
    volumes:
      - ./node_exporter:/app
    command: ["python3", "run_api.py"]
    ports:
      - 9100:9100
    networks:
      - tb_net
    restart: always
    deploy:
      restart_policy:
        condition: any

  mysql:
    image: dingjinlong/mysql:latest
    volumes:
      - ./data/mysql/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - tb_net
    restart: always
    environment: 
          - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: any

  socket:
    image: dingjinlong/node_exporter:latest
    volumes:
      - ./node_exporter:/app
    command: ["python3", "run_socket.py"]
    ports:
      - 5858:5858
    networks:
      - tb_net
    restart: always
    environment: 
          - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: any

  grafana:
    image: dingjinlong/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana/lib/grafana:/var/lib/grafana
      - ./data/grafana/etc/grafana:/etc/grafana

    restart: always
    networks:
      - tb_net
    deploy:
      restart_policy:
        condition: any

networks:
  tb_net:
volumes:
  tb_db:
